; Listing generated by Microsoft (R) Optimizing Compiler Version 19.28.29335.0 

	TITLE	E:\C++\Thecplusplusrepo\C++Fromcherno\math1.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

msvcjmc	SEGMENT
__6505BA17_endbrace@h DB 01H
__769C2E39_math1@cpp DB 01H
msvcjmc	ENDS
PUBLIC	?multiply@@YAHHH@Z				; multiply
PUBLIC	__JustMyCode_Default
EXTRN	@__CheckForDebuggerJustMyCode@4:PROC
EXTRN	__RTC_CheckEsp:PROC
EXTRN	__RTC_InitBase:PROC
EXTRN	__RTC_Shutdown:PROC
;	COMDAT rtc$TMZ
rtc$TMZ	SEGMENT
__RTC_Shutdown.rtc$TMZ DD FLAT:__RTC_Shutdown
rtc$TMZ	ENDS
;	COMDAT rtc$IMZ
rtc$IMZ	SEGMENT
__RTC_InitBase.rtc$IMZ DD FLAT:__RTC_InitBase
rtc$IMZ	ENDS
; Function compile flags: /Odt
;	COMDAT __JustMyCode_Default
_TEXT	SEGMENT
__JustMyCode_Default PROC				; COMDAT
	push	ebp
	mov	ebp, esp
	pop	ebp
	ret	0
__JustMyCode_Default ENDP
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
;	COMDAT ?multiply@@YAHHH@Z
_TEXT	SEGMENT
_result$ = -8						; size = 4
_x$ = 8							; size = 4
_y$ = 12						; size = 4
?multiply@@YAHHH@Z PROC					; multiply, COMDAT
; File E:\C++\Thecplusplusrepo\C++Fromcherno\math1.cpp
; Line 3
	push	ebp
	mov	ebp, esp
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	lea	edi, DWORD PTR [ebp-204]
	mov	ecx, 51					; 00000033H
	mov	eax, -858993460				; ccccccccH
	rep stosd
; File E:\C++\Thecplusplusrepo\C++Fromcherno\endbrace.h
	mov	ecx, OFFSET __6505BA17_endbrace@h
	call	@__CheckForDebuggerJustMyCode@4
; File E:\C++\Thecplusplusrepo\C++Fromcherno\math1.cpp
; Line 5
	mov	eax, DWORD PTR _x$[ebp]
	imul	eax, DWORD PTR _y$[ebp]
	mov	DWORD PTR _result$[ebp], eax
; Line 6
	mov	eax, DWORD PTR _result$[ebp]
; File E:\C++\Thecplusplusrepo\C++Fromcherno\endbrace.h
; Line 1
	pop	edi
	pop	esi
	pop	ebx
	add	esp, 204				; 000000ccH
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
?multiply@@YAHHH@Z ENDP					; multiply
_TEXT	ENDS
END
